GET http://localhost:3000/users
Authorization: Bearer


####
Register
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "",
    "email": "",
    "password": "",
    "confPassword": ""
}

####
Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

####
refresh token
GET http://localhost:3000/token

####
Logout
GET http://localhost:3000/logout